services:
  - type: web
    name: shetkari-ml-service
    runtime: python
    rootDir: ml-service
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
